image: base/archlinux

stages:
    - check

shellcheck:
    stage: check
    before_script:
        - pacman -Sy
        - pacman --noconfirm -S make shellcheck
    script:
        - ./tests/shellcheck-lib.sh
    artifacts:
        paths:
            - play.it-2/lib/libplayit2.sh
