stages:
    - library_check
    - wrapper_check

library_shellcheck:
    stage: library_check
    only:
        - master@play.it/scripts
        - /^staging-.*$/@play.it/scripts
        - tags@play.it/scripts
    before_script:
        - make
    script:
        - ./tests/library_shellcheck.sh

wrapper_shellcheck:
    stage: wrapper_check
    only:
        - master@play.it/scripts
        - /^staging-.*$/@play.it/scripts
        - tags@play.it/scripts
    before_script:
        - make
    script:
        - ./tests/wrapper_shellcheck.sh
