stages:
    - syntax

library_shellcheck:
    stage: syntax
    only:
        - master@play.it/scripts
        - /^staging-.*$/@play.it/scripts
        - tags@play.it/scripts
    before_script:
        - make
    script:
        - ./tests/syntax/library_shellcheck.sh

wrapper_shellcheck:
    stage: syntax
    only:
        - master@play.it/scripts
        - /^staging-.*$/@play.it/scripts
        - tags@play.it/scripts
    before_script:
        - make
    script:
        - ./tests/syntax/wrapper_shellcheck.sh
