Document: play.it
Title: Debian play.it Manual
Author: <insert document author here>
Abstract: This manual describes what play.it is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/play.it/play.it.sgml.gz

Format: postscript
Files: /usr/share/doc/play.it/play.it.ps.gz

Format: text
Files: /usr/share/doc/play.it/play.it.text.gz

Format: HTML
Index: /usr/share/doc/play.it/html/index.html
Files: /usr/share/doc/play.it/html/*.html
